[theme]
primaryColor = "#137f77"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#172b41"
font = "sans serif"

[server]
maxUploadSize = 5

[browser]
gatherUsageStats = false
